### ISSUE TITLE
Reference Parser in Python?

### ISSUE THREAD

**Issue by Mem2019** [favocado/Favocado#2]
It has been mentioned in the paper that IDL/API reference parser in Python is one of the modules, but it seems that this is not in the repo?

Thank you very much.

**Comment by Mipu94** [comment]
There are many kinds of js bindings object such Adobe, mojom, nodejs objects... And some of them are closed sources or these binding objects are not defined by IDL files. So we have decided to unpublic this part since it depends on your target. :)
